# Generated by Django 6.0.4 on 2026-06-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testimony_reactions',
                'unique_together': {('testimony', 'user')},
            },
        ),
    ]
