# Generated by Django 6.0.4 on 2026-06-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_circlemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('regular', 'Regular'), ('premium', 'Premium')], default='free', max_length=15),
        ),
    ]
