# Generated by Django 6.0.4 on 2026-06-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledprayer',
            name='stream_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
