# Generated by Django 6.0.4 on 2026-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_scheduledprayer_stream_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flutterwave_subscription_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
