# Generated by Django 6.0.4 on 2026-08-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_flutterwave_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='circlemessage',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circlemessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
