# Generated by Django 6.0.4 on 2026-08-05 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_circlemessage_image_alter_circlemessage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('amen', '🙏'), ('love', '❤️'), ('fire', '🔥'), ('strength', '💪'), ('peace', '🕊️')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.circlemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_message_reactions',
                'unique_together': {('message', 'user', 'reaction_type')},
            },
        ),
    ]
