# Generated by Django 6.0.4 on 2026-08-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_circlemessagereaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circlemessagereaction',
            unique_together={('message', 'user')},
        ),
    ]
