# Generated by Django 6.0.4 on 2026-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_liveroommessage_liveroomreaction_liveroomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveroomparticipant',
            name='peer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
