# Generated by Django 6.0.4 on 2026-08-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_liveroomparticipant_peer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveAudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_chunks', to='api.scheduledprayer')),
            ],
            options={
                'db_table': 'live_audio_chunks',
                'ordering': ['sequence'],
            },
        ),
    ]
