# Generated by Django 6.0.4 on 2026-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_liveaudiochunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
