# Generated by Django 6.0.4 on 2026-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveaudiochunk',
            name='sequence',
            field=models.BigIntegerField(),
        ),
    ]
