# Generated by Django 6.0.4 on 2026-08-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_comment_options_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
