# Generated by Django 6.0.4 on 2026-08-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_testimony_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circlemessage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
